/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package M6;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Josman
 */
public class JF_Tienda extends javax.swing.JFrame {

    ListaProducto listProducto;
    ListaCatProducto listCat_Product;
    
    public JF_Tienda() {
        initComponents();
        
        //Paneles
        panelPadre.setVisible(true);
        panel1.setVisible(true);   // Formulario
        panel2.setVisible(false);
        
        listProducto = new ListaProducto();
        listCat_Product = new ListaCatProducto();
        
        cargarCategorias();
        
        
        
        
    }
    
    public void Limpiar(){
        txtIDCat.setText("");
        txtNombreCat.setText("");
    }
    
    public void cargarCategorias() {
        DefaultComboBoxModel<String> modelo = new DefaultComboBoxModel<>();
    
        modelo.addElement("Seleccione una categoría"); // opción por defecto

        for (CatProducto list : listCat_Product.catProductos) {
            modelo.addElement(list.getNombreCat());
            System.out.println(list.getNombreCat());
        }

        cbCategoria.setModel(modelo);
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPadre = new javax.swing.JPanel();
        btnRegistro = new javax.swing.JButton();
        btnRegistrarCategoria = new javax.swing.JButton();
        btnListaProducto = new javax.swing.JButton();
        panel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblCategoria = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        cbCategoria = new javax.swing.JComboBox<>();
        txtPrecio = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaListaCat = new javax.swing.JTextArea();
        panel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombreCat = new javax.swing.JTextField();
        txtIDCat = new javax.swing.JTextField();
        btnRegistrarCat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPadre.setBackground(new java.awt.Color(255, 255, 204));

        btnRegistro.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnRegistro.setText("Registrar Producto");
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });

        btnRegistrarCategoria.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnRegistrarCategoria.setText("Registrar Categoria");
        btnRegistrarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarCategoriaActionPerformed(evt);
            }
        });

        btnListaProducto.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnListaProducto.setText("Lista de productos");
        btnListaProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaProductoActionPerformed(evt);
            }
        });

        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblTitulo.setText("Registrar productos");
        panel1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 20, 182, 33));

        lblId.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblId.setText("ID:");
        panel1.add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 109, -1, -1));

        lblNombre.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblNombre.setText("Nombre:");
        panel1.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 152, -1, -1));

        lblCategoria.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblCategoria.setText("Categoria:");
        panel1.add(lblCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 195, -1, -1));

        lblPrecio.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblPrecio.setText("Precio:");
        panel1.add(lblPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 241, -1, -1));
        panel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 106, 202, -1));

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        panel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 149, 202, -1));

        cbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCategoriaActionPerformed(evt);
            }
        });
        panel1.add(cbCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 192, -1, -1));

        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });
        panel1.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 238, 202, -1));

        btnRegistrar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnRegistrar.setText("Registrar");
        panel1.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 297, 119, 53));

        txtAreaListaCat.setColumns(20);
        txtAreaListaCat.setRows(5);
        jScrollPane2.setViewportView(txtAreaListaCat);

        panel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 370, 390, 110));

        panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Registrar Categorias de Productos");
        panel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 340, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("ID:");
        panel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 20, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Nombre:");
        panel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 70, -1));

        txtNombreCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreCatActionPerformed(evt);
            }
        });
        panel2.add(txtNombreCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 180, 30));

        txtIDCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDCatActionPerformed(evt);
            }
        });
        panel2.add(txtIDCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 180, 30));

        btnRegistrarCat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegistrarCat.setText("Registrar");
        btnRegistrarCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarCatActionPerformed(evt);
            }
        });
        panel2.add(btnRegistrarCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 110, 70));

        javax.swing.GroupLayout panelPadreLayout = new javax.swing.GroupLayout(panelPadre);
        panelPadre.setLayout(panelPadreLayout);
        panelPadreLayout.setHorizontalGroup(
            panelPadreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPadreLayout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPadreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegistrarCategoria, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnListaProducto, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRegistro, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(panelPadreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelPadreLayout.createSequentialGroup()
                    .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 156, Short.MAX_VALUE)))
        );
        panelPadreLayout.setVerticalGroup(
            panelPadreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
            .addGroup(panelPadreLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(btnRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRegistrarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnListaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelPadreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPadreLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPadre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPadre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
         mostrarPanel(panel1, panel2);
         //txtAreaListaCat.setText(listCat_Product.mostrarCatProducto1());
         //mostrarPanel(Panel2, Panel3);
    }//GEN-LAST:event_btnRegistroActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void btnRegistrarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarCategoriaActionPerformed
        mostrarPanel(panel2, panel1);
    }//GEN-LAST:event_btnRegistrarCategoriaActionPerformed

    private void btnListaProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnListaProductoActionPerformed

    private void txtNombreCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreCatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreCatActionPerformed

    private void txtIDCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDCatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDCatActionPerformed

    private void btnRegistrarCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarCatActionPerformed
        int id = Integer.parseInt(txtIDCat.getText());
        String nombreCat = txtNombreCat.getText();
        
        CatProducto catPro = new CatProducto(id, nombreCat);
        
        if(catPro.validarID_NoCotener_Caracteres(txtIDCat.getText())){
           listCat_Product.registrarCategoria(catPro);
           Limpiar();
        }else{
            JOptionPane.showMessageDialog(null,
                "Error! El ID debe ser numérico",
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
        }
        txtAreaListaCat.setText(listCat_Product.mostrarCatProducto1());
        cargarCategorias();
        
        
    }//GEN-LAST:event_btnRegistrarCatActionPerformed

    private void cbCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCategoriaActionPerformed

    }//GEN-LAST:event_cbCategoriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_Tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_Tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_Tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_Tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_Tienda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListaProducto;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRegistrarCat;
    private javax.swing.JButton btnRegistrarCategoria;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JComboBox<String> cbCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JPanel panelPadre;
    private javax.swing.JTextArea txtAreaListaCat;
    private javax.swing.JTextField txtIDCat;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreCat;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables

    private void mostrarPanel(javax.swing.JPanel mostrar, javax.swing.JPanel ocultar) {
        ocultar.setVisible(false);
        mostrar.setVisible(true);

        mostrar.repaint(); //los vuelve a dibujar
        mostrar.revalidate(); //ajusta el tamaño y posición de los componentes
    }


}
