/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package M5;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Josman
 */
public class JFRameListaProfesor extends javax.swing.JFrame {

    ListaProfesor listProf;
    
    DefaultTableModel df;
    
    public JFRameListaProfesor() {
        initComponents();
        Principal.setVisible(true);
        Panel1.setVisible(true);   // Formulario
        Panel2.setVisible(false);  // Tabla
        
        listProf = new ListaProfesor();
        
        df = new DefaultTableModel();
        df.addColumn("Cédula");
        df.addColumn("Nombre");
        df.addColumn("Edad");
        df.addColumn("Nivel");

        tblProfesor.setModel(df);
        
        cargarTabla();
        
    }
    
    public void cargarTabla(){
        df.setRowCount(0);
        
        for(Profesor prof: listProf.profesores){
            Object[] fila = new Object[4];
            fila[0] = prof.getCedula();
            fila[1] = prof.getNombre();
            fila[2] = prof.getEdad();
            fila[3] = prof.getMateria();
            
            df.addRow(fila);
        }
    }
    
    public void limpiarLabel(){
        this.txtCedula.setText("");
        this.txtNombre.setText("");
        this.txtEdad.setText("");
        this.txtMateria.setText("");
        
    }
    
    
    public boolean validarNumeracion() {
    try {
        Integer.parseInt(txtEdad.getText());
        return true;
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(
            this,
            "La edad debe ser un número entero",
            "Ventana de Restricción",
            JOptionPane.WARNING_MESSAGE
        );
        txtEdad.requestFocus();
        return false;
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Principal = new javax.swing.JPanel();
        Panel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblCedula = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblEdad = new javax.swing.JLabel();
        lblMateria = new javax.swing.JLabel();
        txtMateria = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        Panel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaDatos = new javax.swing.JTextArea();
        Panel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProfesor = new javax.swing.JTable();
        btnMostrarDatos1 = new javax.swing.JButton();
        btnMostrarDatos2 = new javax.swing.JButton();
        btnFormulario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Principal.setMinimumSize(new java.awt.Dimension(600, 550));
        Principal.setPreferredSize(new java.awt.Dimension(600, 550));
        Principal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel1.setMinimumSize(new java.awt.Dimension(500, 500));
        Panel1.setPreferredSize(new java.awt.Dimension(500, 500));
        Panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Registrar Docente");
        Panel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 210, 60));

        lblCedula.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCedula.setText("Cedula:");
        Panel1.add(lblCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        lblNombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNombre.setText("Nombre:");
        Panel1.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        lblEdad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEdad.setText("Edad:");
        Panel1.add(lblEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        lblMateria.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMateria.setText("Materia:");
        Panel1.add(lblMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));
        Panel1.add(txtMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 310, -1));
        Panel1.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 310, -1));
        Panel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 310, -1));
        Panel1.add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 310, -1));

        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegistrar.setText("Registar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        Panel1.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 110, 60));

        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        Panel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 110, 60));

        Principal.add(Panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 478, 514));

        Panel2.setMinimumSize(new java.awt.Dimension(500, 500));
        Panel2.setPreferredSize(new java.awt.Dimension(500, 500));
        Panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Tabla de Datos");
        Panel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        txtAreaDatos.setColumns(20);
        txtAreaDatos.setRows(5);
        jScrollPane1.setViewportView(txtAreaDatos);

        Panel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 360, 220));

        Principal.add(Panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 480, 514));

        Panel3.setMinimumSize(new java.awt.Dimension(500, 500));
        Panel3.setPreferredSize(new java.awt.Dimension(500, 500));
        Panel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Tabla de Datos");
        Panel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        tblProfesor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblProfesor);

        Panel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 450, 220));

        Principal.add(Panel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 480, 514));

        btnMostrarDatos1.setText("Mostrar Datos 1");
        btnMostrarDatos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarDatos1ActionPerformed(evt);
            }
        });
        Principal.add(btnMostrarDatos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, -1, 60));

        btnMostrarDatos2.setText("Mostrar Datos 2");
        btnMostrarDatos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarDatos2ActionPerformed(evt);
            }
        });
        Principal.add(btnMostrarDatos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, -1, 60));

        btnFormulario.setText("Registro");
        btnFormulario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormularioActionPerformed(evt);
            }
        });
        Principal.add(btnFormulario, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 113, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 14, Short.MAX_VALUE)
                .addComponent(Principal, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        //Limpiar labels:
        limpiarLabel();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        
        if(!validarNumeracion()){
            return;
        }
        
        String cedula = this.txtCedula.getText();
        String nombre = this.txtNombre.getText();
        int edad = Integer.parseInt(this.txtEdad.getText());
        String materia = this.txtMateria.getText();
        
        Profesor profe = new Profesor(cedula, nombre, edad, materia);
        listProf.RegistrarProfesor(profe);
        limpiarLabel();

        
        
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnMostrarDatos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarDatos1ActionPerformed
         mostrarPanel(Panel2, Panel1);
         mostrarPanel(Panel2, Panel3);
         txtAreaDatos.setText(listProf.MostrarProfesor());
    }//GEN-LAST:event_btnMostrarDatos1ActionPerformed

    private void btnMostrarDatos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarDatos2ActionPerformed
        cargarTabla();
        mostrarPanel(Panel3, Panel1);
        mostrarPanel(Panel3, Panel2);
    }//GEN-LAST:event_btnMostrarDatos2ActionPerformed

    private void btnFormularioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormularioActionPerformed
        mostrarPanel(Panel1, Panel2);
        mostrarPanel(Panel1, Panel3);
    }//GEN-LAST:event_btnFormularioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFRameListaProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFRameListaProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFRameListaProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFRameListaProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFRameListaProfesor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel1;
    private javax.swing.JPanel Panel2;
    private javax.swing.JPanel Panel3;
    private javax.swing.JPanel Principal;
    private javax.swing.JButton btnFormulario;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnMostrarDatos1;
    private javax.swing.JButton btnMostrarDatos2;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblMateria;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JTable tblProfesor;
    private javax.swing.JTextArea txtAreaDatos;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtMateria;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

    private void mostrarPanel(javax.swing.JPanel mostrar, javax.swing.JPanel ocultar) {
        ocultar.setVisible(false);
        mostrar.setVisible(true);

        mostrar.repaint(); //los vuelve a dibujar
        mostrar.revalidate(); //ajusta el tamaño y posición de los componentes
    }

    /*    
        modeloTabla.addRow(new Object[]{cedula, nombre, edad});
        mostrar.revalidate(); // ajusta el layout
        mostrar.repaint();    // redibuja la tabla
    */
    
}

